### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by ChaiBapchya** [connerturner/Garnish#1]
- [ ]  Prepare a documentation for users to make use of LinkedIn Markdown editor

**Comment by connerturner** [comment]
Garnish is no longer maintained and is currently incomplete, I'm going to mark this wontfix, but will add it to the project if it gets resurrected.

**Comment by ChaiBapchya** [comment]
I wish to contribute if need be, would want to know the possible reasons why Garnish is no longer maintained if thats fine by you.. Looks like a solution to possible issues people might face more often.. @connerturner

**Comment by connerturner** [comment]
@ChaiBapchya Linkedin added support for a minimal WYSIWYG posts editor which was the equivalent of what this project was trying to achieve, as such it seems a waste of time, also as this would have to be a browser element there is compatibility issues for those who did not have this and would see unstyled markdown etc...

**Comment by ChaiBapchya** [comment]
Oh I see...then it makes sense to shut it..
